name: "Create Service Image"

on:
  push:
    branches:
      - develop
      - release/*
    paths: 
      - 'frontend/**'
      - 'services/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.changes.outputs.changed }} 

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.3

      - name: identify changes
        id: changes
        run: |
          git fetch origin ${{ github.ref }} --depth=1
          changed=$(git diff --name-only origin/${{ github.ref }})
          echo "changed=$changed" >> $GITHUB_OUTPUT
      
  lint:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, services/address-service, services/cart-service, services/catalog-service, services/order-service, services/payment-service, services/tracking-service]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Determine if this service changed
        id: check
        run: |
          echo "changed='${{ needs.detect-changes.outputs.changed }}'"
          if echo "${{ needs.detect-changes.outputs.changed }}" | grep -q "${{ matrix.service }}"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js environment (frontend)
        if: ${{ steps.check.outputs.changed == 'true' && startsWith(matrix.service, 'frontend') }}
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '20'

      - name: Install frontend dependencies
        if: ${{ steps.check.outputs.changed == 'true' && startsWith(matrix.service, 'frontend') }}
        run: npm install
        working-directory: ${{ matrix.service }}

      - name: Run frontend lint
        if: ${{ steps.check.outputs.changed == 'true' && startsWith(matrix.service, 'frontend') }}
        working-directory: ${{ matrix.service }}
        run: |
          if npm run lint -- --help >/dev/null 2>&1; then
            npm run lint
          else
            echo "No frontend lint script defined."
          fi

      - name: Set up Python (service)
        if: ${{ steps.check.outputs.changed == 'true' && !startsWith(matrix.service, 'frontend') }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python lint tools
        if: ${{ steps.check.outputs.changed == 'true' && !startsWith(matrix.service, 'frontend') }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint

      - name: Run Python lint
        if: ${{ steps.check.outputs.changed == 'true' && !startsWith(matrix.service, 'frontend') }}
        run: |
          find ${{ matrix.service }} -name '*.py' | xargs python -m pylint
         
  # unit-test:
  #   runs-on: ubuntu-latest
  # build:
  #   runs-on: ubuntu-latest
  # code-scan:
  #   runs-on: ubuntu-latest
  # deploy:
