name: "setup infra for example app"

on: 
 workflow_dispatch:
   inputs:
     environment:
       type: choice
       default: prod
       options:
         - dev
         - staging
         - prod
     terrafom_command:
       type: choice
       default: apply
       options:
         - apply
         - destroy
 push:
   branches: 
     - main
     - develop
     - release/*
   paths: 
     - infra/terraform/**
     
# permissions: 
#  id-token: write
#  contents: read
 
# env:
#   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#   ARM_USE_OIDC: true
jobs: 
  terraform-apply-plan:
    if: inputs.terrafom_command == 'apply'
    runs-on: ubuntu-latest
    environment: github_terrafrom
    defaults:
      run:
        working-directory: "infra/terraform/"
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      - name: Terraform init
        run: terraform init
        working-directory: "infra/terraform/environments/${{ inputs.environment }}"

      - name: Terraform formate
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file="terraform.tfvars" -out="apply-plan.out"
        working-directory: "infra/terraform/environments/${{ inputs.environment }}"

      - name: Upload tfplan
        uses: actions/upload-artifact@v7.0.1
        with:
          name: tf-apply-plan
          path: "infra/terraform/environments/${{ inputs.environment }}/apply-plan.out"
          retention-days: 1

        
  terraform-apply:
   environment: prod-approval, github_terrafrom
   needs: terraform-apply-plan
   if: inputs.terrafom_command == 'apply'
   runs-on: ubuntu-latest
   defaults:
     run:
       working-directory: "infra/terraform/environments/${{ inputs.environment }}"
   steps:
     - name: checkout
       uses: actions/checkout@v6.0.3

     - name: Download artifact tfplan
       uses: actions/download-artifact@v3.1.0
       with:
         name: tf-apply-plan
         
     - name: Install terraform
       uses: hashicorp/setup-terraform@v2.0.3         

     - name: Terraform Init
       run: terraform init
       
     - name: Terraform formate
       run: terraform fmt

     - name: Terraform validate
       run: terraform validate
       
     - name: Apply Terraform
       run: terraform apply apply-plan.out
       
  # terraform-deploy-plan:
  # terraform-deploy:
  
