name: Build Docker Image

on: 
 workflow_call: 
  inputs:
    working_dir:
      required: true
      type: string

    image_name:
      required: true
      type: string

    image_version:
      required: true
      type: string

jobs:
  build-scane-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Install Trivy
        run: sudo apt-get install -y trivy
        
      - name: Build container image
        run: make build IMAGE_NAME=${{ inputs.image_name }} IMAGE_TAG=${{ inputs.image_version }}

      - name: Scan container image
        run: make scan IMAGE_NAME=${{ inputs.image_name }} IMAGE_TAG=${{ inputs.image_version }}

      - name: Publish Image
        run: make publish
