name: Build Docker Image

on: 
 workflow_call: 
  inputs:
    working_dir:
      required: true
      type: string

    image_name:
      required: true
      type: string

    image_version:
      required: true
      type: string

    client_id:
     required: true
     type: string

    tenant_id:
     type: string
     required: true

    subscription_id:
     type: string
     required: true

permissions: 
 id-token: write
 contents: read

jobs:
  build-scane-and-publish:
    environment: github_terrafrom
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Install Trivy
        run: sudo apt-get install -y trivy

      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: ${{ inputs.client_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}
        
      - name: Build container image
        run: make build IMAGE_NAME=${{ inputs.image_name }} IMAGE_TAG=${{ inputs.image_version }}

      - name: Scan container image
        run: make scan IMAGE_NAME=${{ inputs.image_name }} IMAGE_TAG=${{ inputs.image_version }}

      - name: Publish Image
        run: make publish
